[mod]
apiSchema = "0.1.0"
tag = "scc"
name = "Simple Character Sheet"
version = "0.1.0"
author = "PlanarAlly"
shortDescription = "A simple character sheet for PlanarAlly"

description = """
This mod adds a simple character sheet to PlanarAlly.

It will automatically add a new tab to shapes marked as characters.
"""
